### ISSUE TITLE
Zoom + Drag offset not accounted for

### ISSUE THREAD

**Issue by DragonFighter603** [Spydr06/logicrs#1]
# Issue
Position is not adjusted for the offset created by zooming
![image](https://user-images.githubusercontent.com/75088766/215268366-3b2d813f-f49e-465e-b0d1-6bb7d8f6e7e9.png)
![image](https://user-images.githubusercontent.com/75088766/215268380-84657152-76ba-431a-9e1f-adc83254377c.png)
# Reproduction
holding down LMB on a component/wire and scroll to zoom (see images)
# Potential Fix
Centering zoom on mouse pointer would make the issue disappear since the offset would be 0. Additionally, it is a more natural way to zoom

**Comment by Spydr06** [comment]
With 88a22f9d35b1f2219f12873ca230af7b1f73606d, zooming is now centered around the mouse. The issue is still there, however.
