### ISSUE TITLE
Deleting modules doesn't work reliably

### ISSUE THREAD

**Issue by NeeeZeee** [Spydr06/logicrs#22]
RIGHT Click -> Delete on (connected) modules often has no effect. Deleting the gate again after moving it usually works.

**Comment by Spydr06** [comment]
Fixed it in https://github.com/Spydr06/logicrs/commit/a9f474b1deeeca67652955e17175874bcdec9d71

**Comment by Spydr06** [comment]
New version for download (0.1.1):
https://github.com/Spydr06/logicrs/releases/tag/beta-0.1.1
