### ISSUE TITLE
Module can be used in its own definition [FUTURE BUG]

### ISSUE THREAD

**Issue by DragonFIghter603** [Spydr06/logicrs#6]
# Issue 
A module being used in its own definition could lead to infinite recursion. 
Note that this is potentially not true for all configurations.
I has to be checked recursively for modules using modules that use the current module 
(aka recursion where the loop is larger than 1 element)
![image](https://user-images.githubusercontent.com/75088766/215270093-3650e96c-2514-4863-b484-38f7f21114ba.png)

**Comment by Spydr06** [comment]
Fixed by having an error reported to the user when recursion is detected
